### ISSUE TITLE
angular_media enhancements

### ISSUE THREAD

**Issue by jlyon** [proudcity/proud#80]
- [ ] Clean up UI: make getting to crop easier
- [ ] Crop: use image formatter instead of using full image 
- [ ] EPIC: integrate with paid stock image service (getty images, [istockphoto](http://www.gettyimagesaffiliates.com/istock-api-widget/))
- [ ] EPIC: come up with better angular plugin system
